=== oasis-tcs/legalxml-courtfiling-5.0-spec/ecf-v5.0-cs01/schema/policyresponse.xsd
<?xml version="1.0" encoding="US-ASCII"?>
<!--
     Electronic Court Filing Version 5.0
     Committee Specification 01
     18 April 2019
     Copyright (c) OASIS Open 2019. All Rights Reserved.
     Source: https://docs.oasis-open.org/legalxml-courtfiling/ecf/v5.0/cs01/schema/
     Latest version of narrative specification: http://docs.oasis-open.org/legalxml-courtfiling/ecf/v5.0/ecf-v5.0.html
     TC IPR Statement: https://www.oasis-open.org/committees/legalxml-courtfiling/ipr.php
-->
<!-- Generated by BOUML niemtools plug_out (https://github.com/cabralje/niem-tools) -->
<xs:schema targetNamespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse"
 xmlns="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ecf="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/ecf" xmlns:nc="http://release.niem.gov/niem/niem-core/4.0/" xmlns:niem-xs="http://release.niem.gov/niem/proxy/xsd/4.0/" xmlns:policyresponse="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse" xmlns:structures="http://release.niem.gov/niem/structures/4.0/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:clsa="http://reference.niem.gov/niem/specification/code-lists/1.0/code-lists-schema-appinfo/" xmlns:ct="http://release.niem.gov/niem/conformanceTargets/3.0/" xmlns:term="http://release.niem.gov/niem/localTerminology/3.0/" ct:conformanceTargets="http://reference.niem.gov/niem/specification/naming-and-design-rules/3.0/#ExtensionSchemaDocument http://reference.niem.gov/niem/specification/code-lists/1.0/#SchemaDocument" elementFormDefault="qualified" attributeFormDefault="unqualified" version="5.0">
<xs:annotation>
<xs:documentation> Schema for namespace https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse</xs:documentation>
</xs:annotation><xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd"/><xs:import namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/ecf" schemaLocation="ecf.xsd"/><xs:import namespace="http://release.niem.gov/niem/niem-core/4.0/" schemaLocation="niem\niem-core\4.0\niem-core.xsd"/><xs:import namespace="http://release.niem.gov/niem/proxy/xsd/4.0/" schemaLocation="niem\proxy\xsd\4.0\xs.xsd"/><xs:import namespace="http://release.niem.gov/niem/structures/4.0/" schemaLocation="niem\utility\structures\4.0\structures.xsd"/><xs:complexType name="CodeListExtensionType">
<xs:annotation>
<xs:documentation>A value allowed for the parent identified element, and associated information</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="policyresponse:ExtensionType">
<xs:sequence>
<xs:element ref="policyresponse:ECFElementNameText" minOccurs="0" maxOccurs="1"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="DevelopmentPolicyType">
<!--Reference nc:Metadata with policyresponse:DevelopmentPolicy/@structures:metadata--><xs:annotation>
<xs:documentation>Within Court Policy, the policies that are accessed by a person or organization developing an applications or configuring an application to interact with a court for the purpose of structuring the interactions with that court.  This information is needed once and is not accessed dynamically while interacting with the court.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="policyresponse:AcceptConfidentialFilingsIndicator" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:AcceptDocumentsRequiringFeesIndicator" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:AcceptMultipleLeadDocumentsIndicator" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:FilerRequiredToServeIndicator" minOccurs="0" maxOccurs="1"/>
<xs:element ref="policyresponse:FilingFeesMayBeApplicableIndicator" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:MajorDesignElement" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:MaximumAllowedAttachmentPageQuantity" minOccurs="0" maxOccurs="1"/>
<xs:element ref="policyresponse:MaximumAllowedAttachmentSize" minOccurs="0" maxOccurs="1"/>
<xs:element ref="policyresponse:MaximumAllowedMessageSize" minOccurs="0" maxOccurs="1"/>
<xs:element ref="policyresponse:SchemaExtension" minOccurs="0" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:SupportedCaseCategories" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:SupportedSignaturesProfiles" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:URLAttachmentSupportedIndicator" minOccurs="1" maxOccurs="1"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="ExtensionType">
<xs:annotation>
<xs:documentation>A structure representing a court-specific data structure passed to a particular operation on a particular MDE.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="policyresponse:ExtensionCanonicalURI" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:ExtensionCanonicalVersionURI" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:ExtensionLocationURI" minOccurs="1" maxOccurs="1"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="GetPolicyResponseMessageType">
<!--Reference nc:Metadata with policyresponse:SchemaExtension/@structures:metadata; Reference nc:Metadata with policyresponse:GetPolicyResponseMessage/@structures:metadata--><xs:annotation>
<xs:documentation>The response to a request for a court Court Policy.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="ecf:ResponseMessageType">
<xs:sequence>
<xs:element ref="nc:Metadata" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:DevelopmentPolicy" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:GetPolicyResponseMessageAugmentationPoint" minOccurs="0" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:PolicyVersionID" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:RuntimePolicy" minOccurs="1" maxOccurs="1"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="MajorDesignElementType">
<xs:annotation>
<xs:documentation>An ECF Major Design Element (MDE)</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="policyresponse:MajorDesignElementLocationID" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:MajorDesignElementTypeCode" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:SupportedOperations" minOccurs="1" maxOccurs="1"/>
<xs:element ref="policyresponse:SupportedServiceInteractionProfiles" minOccurs="1" maxOccurs="1"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="RuntimePolicyType">
<!--Reference nc:Metadata with policyresponse:RuntimePolicy/@structures:metadata--><xs:annotation>
<xs:documentation>Within Court Policy, the policies that are accessed dynamically by applications interacting with a court.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="ds:KeyInfo" minOccurs="0" maxOccurs="1"/>
<xs:element ref="policyresponse:CodeListExtension" minOccurs="0" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="SchemaExtensionType">
<!--Reference nc:Metadata in policyresponse:SchemaExtension/@structures:metadata; Genericode code list MajorDesignElementTypeCode.gc--><xs:annotation>
<xs:documentation>A structure representing the court-specific extensions for the court associated with this Court Policy.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="policyresponse:ExtensionType">
<xs:sequence>
<xs:element ref="policyresponse:ExtensionElementName" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:MajorDesignElementTypeCode" minOccurs="1" maxOccurs="unbounded"/>
<xs:element ref="policyresponse:OperationNameCode" minOccurs="1" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="SupportedCaseCategoriesType">
<!--Genericode code list CaseTypeCode.gc--><xs:annotation>
<xs:documentation>A structure containing indicators that signal support by the e-filing system for each ECF case type.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="ecf:CaseTypeCode" minOccurs="1" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="SupportedOperationsType">
<xs:annotation>
<xs:documentation>A structure containing indicators that signal support by the e-filing system for optional ECF operations. E.g. particular queries.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="policyresponse:OperationNameCode" minOccurs="1" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="SupportedServiceInteractionProfilesType">
<!--Genericode code list ServiceInteractionProfileCode.gc--><xs:annotation>
<xs:documentation>A message profile approved for use with ECF by the OASIS LegalXML Member Section Electronic Court Filing Technical Committee that are supported in a particualr court.  Identifiers for supported profiles are set forth in Court Policy.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="ecf:ServiceInteractionProfileCode" minOccurs="1" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:complexType name="SupportedSignatureProfilesType">
<!--Genericode code list SignatureProfileCode.gc--><xs:annotation>
<xs:documentation>A signature profile approved for use with ECF 3.0 by the OASIS LegalXML Member Section Electronic Court Filing Technical Committee that are supported in a particualr court.  Identifiers for supported profiles are set forth in Court Policy.</xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="structures:ObjectType">
<xs:sequence>
<xs:element ref="ecf:SignatureProfileCode" minOccurs="1" maxOccurs="unbounded"/>

</xs:sequence>
</xs:extension>

</xs:complexContent>
</xs:complexType>
<xs:element name="AcceptConfidentialFilingsIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Whether the court will accept electronic filing of documents for which the filer requests confidential or sealed treatment by the court.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="AcceptDocumentsRequiringFeesIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Whether the court will accept electronic filing of documents requiring filing fees.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="AcceptMultipleLeadDocumentsIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Does court accept placing multiple lead documents in a single message</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="CodeListExtension" type="policyresponse:CodeListExtensionType">
<!--Reference nc:Metadata in policyresponse:CodeListExtension/@structures:metadata-->
<xs:annotation>
<xs:documentation>A value allowed for the parent identified element, and associated information.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="DevelopmentPolicy" type="policyresponse:DevelopmentPolicyType">

<xs:annotation>
<xs:documentation>The response to a request for a court Court Policy.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ECFElementNameText" type="nc:TextType">

<xs:annotation>
<xs:documentation>The data element for which an allowable set of values is enumerated.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ExtensionCanonicalURI" type="niem-xs:anyURI">

<xs:annotation>
<xs:documentation>A court extension to ECF.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ExtensionCanonicalVersionURI" type="niem-xs:anyURI">

<xs:annotation>
<xs:documentation>A structure representing the specific court extension.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ExtensionElementName" type="niem-xs:anyURI">

<xs:annotation>
<xs:documentation>The element(s) in the extension schema that are are the root of the extension and substitute for an extension (augmentation) point.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="ExtensionLocationURI" type="niem-xs:anyURI">

<xs:annotation>
<xs:documentation>An XML Schema document that defines the allowable structure of the court-specific argument to this MDE operation.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="FilerRequiredToServeIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Indicator whether the filer is required to serve</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="FilingFeesMayBeApplicableIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Indicates whether fees may be required for some filings.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="GetPolicyResponseMessage" type="policyresponse:GetPolicyResponseMessageType">

<xs:annotation>
<xs:documentation>The response to a request for a court Court Policy.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="GetPolicyResponseMessageAugmentationPoint" abstract="true">

<xs:annotation>
<xs:documentation>An extension point for the enclosing message.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="MajorDesignElement" type="policyresponse:MajorDesignElementType">

<xs:annotation>
<xs:documentation>An ECF major design element (MDE)</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="MajorDesignElementLocationID" type="nc:IdentificationType">

<xs:annotation>
<xs:documentation>The unique URL location of a major design element.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="MajorDesignElementTypeCode" type="niem-xs:normalizedString">
<!--Genericode code list MajorDesignElementTypeCode.gc-->
<xs:annotation>
<xs:documentation>Name of a major design element.</xs:documentation>
<xs:appinfo><clsa:SimpleCodeListBinding codeListURI="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/MajorDesignElementTypeCode"/> </xs:appinfo></xs:annotation>
</xs:element>
<xs:element name="MaximumAllowedAttachmentPageQuantity" type="nc:NumericType">

<xs:annotation>
<xs:documentation>The maximum allowed number of pages in an attachment.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="MaximumAllowedAttachmentSize" type="nc:MeasureType">

<xs:annotation>
<xs:documentation>The maximum allowed attachment size, in bytes.  Does not appear if there is no maximum.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="MaximumAllowedMessageSize" type="nc:MeasureType">

<xs:annotation>
<xs:documentation>Maximum allowed size of the Court Filing Message Stream, in bytes.  Does not appear if there is no maximum.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="OperationNameCode" type="niem-xs:normalizedString">
<!--Genericode code list OperationNameCode.gc-->
<xs:annotation>
<xs:documentation>Indicates whether the e-filing system supports a certain operation.</xs:documentation>
<xs:appinfo><clsa:SimpleCodeListBinding codeListURI="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/OperationNameCode"/> </xs:appinfo></xs:annotation>
</xs:element>
<xs:element name="PolicyVersionID" type="nc:IdentificationType">

<xs:annotation>
<xs:documentation>The version of court policy reported by this message.  Up to the court to define the format of this, and describe in human-readable court policy.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="RuntimePolicy" type="policyresponse:RuntimePolicyType">

<xs:annotation>
<xs:documentation>Within Court Policy, the policies that are accessed dynamically by applications interacting with a court.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="SchemaExtension" type="policyresponse:SchemaExtensionType">

<xs:annotation>
<xs:documentation>A structure representing the court-specific extensions for this court</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="SupportedCaseCategories" type="policyresponse:SupportedCaseCategoriesType">

<xs:annotation>
<xs:documentation>A list of ECF case types.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="SupportedOperations" type="policyresponse:SupportedOperationsType">

<xs:annotation>
<xs:documentation>A structure containing indicators that signal support by the e-filing system for optional ECF operations. E.g. particular queries</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="SupportedServiceInteractionProfiles" type="policyresponse:SupportedServiceInteractionProfilesType">

<xs:annotation>
<xs:documentation>A signature profile approved for use with ECF by the OASIS LegalXML Member Section Electronic Court Filing Technical Committee that is supported by this court.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="SupportedSignaturesProfiles" type="policyresponse:SupportedSignatureProfilesType">

<xs:annotation>
<xs:documentation>A signature profile approved for use with ECF by the OASIS LegalXML Member Section Electronic Court Filing Technical Committee that is supported by this court.</xs:documentation>
</xs:annotation>
</xs:element>
<xs:element name="URLAttachmentSupportedIndicator" type="niem-xs:boolean">

<xs:annotation>
<xs:documentation>Whether court allows attachments via remote URLs.</xs:documentation>
</xs:annotation>
</xs:element>
</xs:schema>

=== oasis-tcs/legalxml-courtfiling-5.0-spec/ecf-v5.0-cs01/examples/policyresponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
     Electronic Court Filing Version 5.0
     Committee Specification 01
     18 April 2019
     Copyright (c) OASIS Open 2019. All Rights Reserved.
     Source: https://docs.oasis-open.org/legalxml-courtfiling/ecf/v5.0/cs01/examples/
     Latest version of narrative specification: http://docs.oasis-open.org/legalxml-courtfiling/ecf/v5.0/ecf-v5.0.html
     TC IPR Statement: https://www.oasis-open.org/committees/legalxml-courtfiling/ipr.php 
-->
<!-- Modifications:
	
		Added nc:IdentificationCategoryDescriptionText and nc:IdentificationSourceText for messageID.
		Added message Id from the request message (e.g. GetPolicyRequestMessage) as required per specification.

-->
<policyresponse:GetPolicyResponseMessage xmlns:policyresponse="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse" xmlns:nc="http://release.niem.gov/niem/niem-core/4.0/" xmlns:j="http://release.niem.gov/niem/domains/jxdm/6.1/" xmlns:ecf="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/ecf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/policyresponse ../schema/policyresponse.xsd">
	<nc:DocumentIdentification>
		<nc:IdentificationID>10</nc:IdentificationID>
		<nc:IdentificationCategoryDescriptionText>messageID</nc:IdentificationCategoryDescriptionText>
		<nc:IdentificationSourceText>CourtPolicy</nc:IdentificationSourceText>
	</nc:DocumentIdentification>
	<nc:DocumentIdentification>
		<nc:IdentificationID>123456ABC</nc:IdentificationID>
		<nc:IdentificationCategoryDescriptionText>messageID</nc:IdentificationCategoryDescriptionText>
		<nc:IdentificationSourceText>FilingAssembly</nc:IdentificationSourceText>
	</nc:DocumentIdentification>
	<ecf:DocumentAugmentation>
		<ecf:DocumentFiler>
			<nc:EntityPerson>
				<ecf:PersonAugmentation>
					<ecf:ParticipantID>
						<nc:IdentificationID>10</nc:IdentificationID>
					</ecf:ParticipantID>
				</ecf:PersonAugmentation>
			</nc:EntityPerson>
		</ecf:DocumentFiler>
	</ecf:DocumentAugmentation>
	<ecf:SendingMDELocationID>
		<nc:IdentificationID>https://efilingmanager.com:8000</nc:IdentificationID>
	</ecf:SendingMDELocationID>
	<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
	<j:CaseCourt>
		<nc:OrganizationIdentification>
			<nc:IdentificationID>01</nc:IdentificationID>
		</nc:OrganizationIdentification>
		<j:CourtName>King County Superior Court</j:CourtName>
	</j:CaseCourt>
	<nc:DocumentPostDate>
		<nc:DateTime>2007-06-06T14:20:47.0Z</nc:DateTime>
	</nc:DocumentPostDate>
	<nc:Metadata>
		<nc:EffectiveDate>
			<nc:DateTime>2007-06-06T14:20:47.0Z</nc:DateTime>
		</nc:EffectiveDate>
		<nc:LastUpdatedDate>
			<nc:DateTime>2007-06-06T14:20:47.0Z</nc:DateTime>
		</nc:LastUpdatedDate>
	</nc:Metadata>
	<policyresponse:DevelopmentPolicy>
		<policyresponse:AcceptConfidentialFilingsIndicator>true</policyresponse:AcceptConfidentialFilingsIndicator>
		<policyresponse:AcceptDocumentsRequiringFeesIndicator>true</policyresponse:AcceptDocumentsRequiringFeesIndicator>
		<policyresponse:AcceptMultipleLeadDocumentsIndicator>false</policyresponse:AcceptMultipleLeadDocumentsIndicator>
		<policyresponse:FilingFeesMayBeApplicableIndicator>true</policyresponse:FilingFeesMayBeApplicableIndicator>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://efsp.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>FilingAssembly</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>NotifyCourtDate</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>NotifyFilingReviewComplete</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://efsp.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>Service</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>ServeFiling</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>ServeProcess</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://efilingmanager.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>CourtPolicy</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>GetPolicy</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://efilingmanager.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>FilingReview</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>CancelFiling</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetFeesCalculation</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetFilingList</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetFilingStatus</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetServiceInformation</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>NotifyDocketingComplete</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>NotifyDocumentStampInformation</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>ReviewFiling</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://courtscheduling.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>CourtScheduling</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>GetCourtSchedule</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>NotifyCourtDate</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>ReserveCourtDate</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MajorDesignElement>
			<policyresponse:MajorDesignElementLocationID>
				<nc:IdentificationID>https://courtrecord.com:8000</nc:IdentificationID>
			</policyresponse:MajorDesignElementLocationID>
			<policyresponse:MajorDesignElementTypeCode>CourtRecord</policyresponse:MajorDesignElementTypeCode>
			<policyresponse:SupportedOperations>
				<policyresponse:OperationNameCode>AllocateCourtDate</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>DocumentStampInformation</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetCase</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetCaseList</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetDocument</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>GetServiceInformation</policyresponse:OperationNameCode>
				<policyresponse:OperationNameCode>RecordDocketing</policyresponse:OperationNameCode>
			</policyresponse:SupportedOperations>
			<policyresponse:SupportedServiceInteractionProfiles>
				<ecf:ServiceInteractionProfileCode>urn:oasis:names:tc:legalxml-courtfiling:schema:xsd:WebServicesMessaging-5.0</ecf:ServiceInteractionProfileCode>
			</policyresponse:SupportedServiceInteractionProfiles>
		</policyresponse:MajorDesignElement>
		<policyresponse:MaximumAllowedAttachmentPageQuantity>1000</policyresponse:MaximumAllowedAttachmentPageQuantity>
		<policyresponse:MaximumAllowedAttachmentSize>
